
CREATE TABLE difficulty (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO difficulty (name) VALUES ('Facile'), ('Intermédiaire'), ('Difficile');

CREATE TABLE user (
   id INT AUTO_INCREMENT PRIMARY KEY,
   pseudo VARCHAR(50) NOT NULL,
   username VARCHAR(50) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL,
   email VARCHAR(100) NOT NULL UNIQUE,
   role VARCHAR(20) NOT NULL DEFAULT 0,
   civility INT NOT NULL DEFAULT 0 CHECK (civility IN (0, 1, 2)),
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO user (pseudo, username, password, email, role)
VALUES ('GastroGeek', 'Ewan', 'password', 'ewan@outlook.fr', 'admin')
,('Chef_Gourmand', 'Kevin', 'password','kevin@outlook.fr', 'user'),
('PatissierePoetique','Anais', 'password', 'anais@outlook.fr','user');

CREATE TABLE recipe (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    difficulty_id INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description text NOT NULL,
    cooking_time INT NOT NULL,
    preparation_time INT NOT NULL,
    instruction text NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE,
    FOREIGN KEY (difficulty_id) REFERENCES Difficulty(id)
);

INSERT INTO recipe (user_id, difficulty_id, title, description, cooking_time, preparation_time, instruction) VALUES (3, 1, "Quiche Thon et tomates","Une quiche savoureuse et facile à réaliser, à base de thon et de tomates fraîches, parfaite pour un repas léger ou un pique-nique.", 60, 20, 'lorem'), (2, 2, "Lasagnes bolognaise","Des lasagnes à la bolognaise classiques, avec une sauce riche en viande hachée, sauce tomate et une béchamel crémeuse. Un plat italien incontournable et généreux." , 60, 60, 'lorem'), (2, 1, "Toast foie gras", "Le foie gras est un mets délicat français, préparé à partir du foie d'oie ou de canard engraissé. Il est apprécié pour sa texture fondante et son goût riche et subtil.", 2, 5, 'lorem'), (2, 2, "Tarte Tatin", "La Tarte Tatin est une célèbre tarte aux pommes caramélisées à l'envers, cuite au four. Elle est croquante et fondante à la fois.", 45, 30, 'lorem'), (3, 1, "Salade César", "La salade César est une salade classique composée de laitue romaine, de croûtons, de parmesan et d'une sauce à base de mayonnaise et d'anchois.", 0, 15, 'lorem'), (2, 2, "Bœuf Bourguignon", "Un plat traditionnel français à base de bœuf mijoté dans une sauce au vin rouge, agrémenté de légumes comme les carottes, champignons et oignons.", 180, 45, 'lorem'), (2, 3, "Soufflé au fromage", "Un soufflé au fromage est un plat aérien à base de fromage râpé et d'œufs battus en neige. Il gonfle à la cuisson pour un résultat léger et moelleux.", 25, 20, 'lorem'), (3, 2, "Poulet au curry", "Un plat épicé à base de morceaux de poulet mijotés dans une sauce au curry crémeuse. Parfait pour un repas savoureux et rapide.", 40, 15, 'lorem'), (3, 1, "Omelette aux champignons", "Une omelette simple et savoureuse aux champignons sautés. Idéale pour un repas léger et rapide.", 5, 10, 'lorem'),(2, 2, "Pâtes carbonara", "Un classique italien, les pâtes carbonara sont préparées avec des œufs, du parmesan, du lard et beaucoup de poivre.", 20, 10, 'lorem'), (3, 3, "Canard à l'orange", "Un plat sophistiqué où le canard est cuit avec une sauce à base d'orange pour un goût sucré-salé exquis.", 60, 30, 'lorem'), (1, 1, "Crêpes", "Les crêpes françaises sont fines et délicates, parfaites pour être servies avec du sucre, de la confiture ou du chocolat.", 10, 5, 'lorem'), (3, 2, "Ratatouille", "Un ragoût de légumes du sud de la France, composé principalement d'aubergines, de courgettes, de poivrons et de tomates.", 60, 30, 'lorem');


CREATE TABLE ingredient (
  id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(100) NOT NULL UNIQUE
 );

INSERT INTO ingredient (name) VALUES 
('ail'),
('artichaut'),
('asperge'),
('aubergine'),
('basilic'),
('betterave'),
('betterave chioggia'),
('blette'),
('brocoli'),
('carotte'),
('carotte violette'),
('céleri'),
('champignon de Paris'),
('champignon portobello'),
('champignon shiitake'),
('chayotte'),
('chicorée'),
('chou chinois'),
('chou de Bruxelles'),
('chou-fleur'),
('chou-rave'),
('chou rouge'),
('chou vert'),
('ciboulette'),
('coriandre'),
('cresson'),
('crosne'),
('courge butternut'),
('courge spaghetti'),
('courgette'),
('daikon'),
('endive'),
('epinard'),
('fève'),
('fenouil'),
('haricot vert'),
('kale'),
('laitue'),
('laurier'),
('mâche'),
('navet'),
('oignon'),
('pak-choï'),
('patate douce'),
('patisson'),
('petit pois'),
('pois chiche'),
('pois mange-tout'),
('poire de terre'),
('poireau'),
('poivron jaune'),
('poivron rouge'),
('poivron vert'),
('potiron'),
('radicchio'),
('radis'),
('radis noir'),
('romaine'),
('roquette'),
('rutabaga'),
('salsifis'),
('salicorne'),
('scarole'),
('thym'),
('topinambour'),
('tomates'),
('abricot'),
('ananas'),
('avocat'),
('banane'),
('cerise'),
('citron'),
('clémentine'),
('coco'),
('datte'),
('figue'),
('fraise'),
('framboise'),
('fruit de la passion'),
('grenade'),
('groseille'),
('kiwi'),
('kumquat'),
('litchi'),
('mandarine'),
('mangue'),
('melon'),
('mirabelle'),
('mûre'),
('myrtille'),
('nectarine'),
('noisette'),
('noix'),
('orange'),
('pamplemousse'),
('papaye'),
('pastèque'),
('pêche'),
('poire'),
('pomme'),
('prune'),
('quetsche'),
('raisin'),
('raisin sec'),
('rhubarbe'),
('thon'),
('yuzu'),
('beurre'),
('sucre'),
('farine'),
('Œufs'),
('lait'),
('gélatine'),
('crème liquide entière'),
('sucre glace'),
('extrait de vanille'),
('pâte brisée'),
('crème fraîche'),
('gruyère'),
('moutarde'),
('boeuf hachée'),
('tomates concassées'),
('concentré de tomates'),
('vin rouge'),
('huile d olive'),
('feuilles de lasagnes'),
('parmesan'),
('muscade'),
('pain de campagne'),
('confiture de figues'),
('fleur de sel'),
('poivre'),
('sel'),
('pâte feuilletée'),
('eau'),
('origan');



 CREATE TABLE Recipe_Ingredient (
    recipe_id INT NOT NULL,
    quantity DECIMAL(10,2),
    unit VARCHAR(20),
    ingredient_id INT NOT NULL,
    PRIMARY KEY (recipe_id, ingredient_id),
    FOREIGN KEY (recipe_id) REFERENCES Recipe(id) ON DELETE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES Ingredient(id) ON DELETE CASCADE
); 

INSERT INTO recipe_ingredient (recipe_id, quantity, unit, ingredient_id ) 
VALUES (1, 1, '', 117), (1, 1, 'cas de', 120), (1, 1, 'boite de', 106 ), (1, 2, "", 66 ), (1, 200, 'ml de', 118 ), (1, 100, 'g', 119), (1, 3, '', 111), (1, 1, 'pincée de', 133), (1, 1, 'pincée de', 132);

INSERT INTO recipe_ingredient (recipe_id, quantity, unit, ingredient_id ) 
 VALUES (2, 300, 'g', 121), (2, 1, '', 42), (2, 2, 'gousses d', 1), (2, 400, 'g de', 122), (2, 1, 'cas de', 123), (2, 1, '', 10), (2, 1, 'branche de', 12), (2, 100, 'ml de', 124), (2, 1, 'cas d', 125), (2, 1, 'cas d', 64), (2, 1, 'cas d', 136), (2, 50, 'g de', 108), (2, 50, 'g de', 110), (2, 500, 'ml de', 112), (2, 1, 'pincée de', 133), (2, 1, 'pincée de', 132), (2, 1, 'pincée de', 128), (2, 100, 'g de', 119), (2, 9, '', 126);